#!/usr/bin/env bash
# this script creates a story based on /etc/passwd
while IFS=':' read -r username password uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
