#!/usr/bin/env bash
# this script displays the content of the current directory, but only the part of the name after the first dash is displayed
list="$(ls -1)"
for i in $list; do
  cut -d '-' -f2- <<< "$i"
done
